/// Flutter icons Custom
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom
///      fonts:
///       - asset: fonts/Custom.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom {
  Custom._();

  static const _kFontFam = 'Custom';

  static const IconData dice_six_faces_two = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData dice_twenty_faces_twenty = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData inverted_dice_1 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData inverted_dice_2 = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData inverted_dice_3 = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData inverted_dice_4 = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData inverted_dice_5 = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData inverted_dice_6 = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData perspective_dice_five = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData perspective_dice_four = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData perspective_dice_one = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData perspective_dice_six = const IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_five = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_four = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_one = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_random = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_six = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_three = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData perspective_dice_six_faces_two = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData perspective_dice_three = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData perspective_dice_two = const IconData(0xe814, fontFamily: _kFontFam);
  static const IconData rolling_dice_cup = const IconData(0xe815, fontFamily: _kFontFam);
  static const IconData rolling_dices = const IconData(0xe816, fontFamily: _kFontFam);
  static const IconData cubes = const IconData(0xe817, fontFamily: _kFontFam);
  static const IconData d4 = const IconData(0xe818, fontFamily: _kFontFam);
  static const IconData d10 = const IconData(0xe819, fontFamily: _kFontFam);
  static const IconData d12 = const IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData dice_eight_faces_eight = const IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData dice_six_faces_five = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData dice_six_faces_four = const IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData dice_six_faces_one = const IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData dice_six_faces_six = const IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData dice_six_faces_three = const IconData(0xe820, fontFamily: _kFontFam);
}
